name: Deploy to my lightsail instance

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: my-tide-app
  DOCKERHUB_USERNAME: scottstef
  CONTAINER_NAME: tide-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image to DH
      run: 
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Deploy via SSH to Lightsail Instance
      uses: appleboy/ssh-action@master # A popular action for SSH
      with:
        host: ${{ secrets.LIGHTSAIL_SSH_HOST }}        # Your Lightsail Public IP as a GitHub Secret
        username: bitnami                   # Your Lightsail instance username
        key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}  # Your Lightsail instance's SSH private key as a GitHub Secret
        script: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ env.DOCKERHUB_USERNAME }} --password-stdin

          # Pull the new image
          docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

          # Stop and remove the old container (if running)
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

          # Run the new container
          docker run -p 5000:5000 -d --name ${{ env.CONTAINER_NAME }} \
            -e PIRATE_WEATHER_API_KEY="${{ secrets.PIRATE_WEATHER_API_KEY_GH }}" \
            -e OPENCAGE_API_KEY="${{ secrets.OPENCAGE_API_KEY_GH }}" \
            -e FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY_GH }}" \
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
